# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 09:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teaminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(max_length=256)),
                ('member2', models.CharField(blank=True, max_length=256)),
                ('collegename', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('totalscore', models.PositiveIntegerField(blank=True, default=0)),
                ('last_submit_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
