# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_teaminfo_total_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('ans', models.CharField(max_length=256)),
            ],
        ),
    ]
