# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
