# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-01 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180401_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
