# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-01 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
