# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-09 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20180309_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='name',
            new_name='url',
        ),
    ]
